name: lint-test-build
on: push
jobs:
  basic:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: install dependencies
        run: npm ci
      - name: lint
        run: npm lint
      - name: test
        run: npm test
      - name: build
        run: npm build

