name: Test And Deploy
on: 
  pull_request:
    types: 
      - opened
      - edited
    branches: 
      - main
    paths:
      - '.github/workflows/*'
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/*'
  workflow_dispatch:
jobs:
  Test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3
      - name: install dependencies
        run: npm ci
      - name: lint
        run: npm run lint
      - name: test
        run: npm run test
      - name: build
        run: npm run build
      - name: deploy
        run: echo "deploying"
    
