name: Test And Deploy
on: 
  pull_request:
    types: 
      - opened
      - edited
    branches: 
      - main
    paths:
      - '.github/workflows/*'
  push:
    branches: 
      - 'Test-*'
    paths:
      - '.github/workflows/*'
  workflow_dispatch:
jobs:
  Test-and-deploy:
    runs-on: ubuntu-latest
    outputs:
      script-file: ${{ steps.get_filename.outputs.script-file }}
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3
      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: install dependencies
        run: npm ci
      - name: lint
        run: npm run lint
      - name: test
        run: npm run test
      - name: build
        run: npm run build
      - name: Publish JS filename
        id: get_filename
        run: find dist/assets/*.js -type f -execdir echo 'script-file={}' >> $GITHUB_OUTPUT ';'
      - name: deploy
        run: echo "deploying"
  Deploy-The-App:
    runs-on: ubuntu-latest
    needs: Test-and-deploy
    steps:
      - name: echo JS file name
        run: echo "${{ needs.Test-and-deploy.outputs.script-file }}"
      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: install dependencies
        run: npm ci
  Test-new:
    runs-on: ubuntu-latest
    needs: Deploy-The-App
    steps:
      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: install dependencies
        run: npm ci
    
